version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql_db
    ports:
      - "3310:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: bsmart_db
      MYSQL_USER: bsmartdev
      MYSQL_PASSWORD: 1234
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
